# Generated by Django 5.1.7 on 2025-04-25 15:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=32, verbose_name="标题")),
                ("count", models.IntegerField(verbose_name="人数")),
            ],
        ),
        migrations.CreateModel(
            name="EquipList",
            fields=[
                ("equip_id", models.AutoField(primary_key=True, serialize=False)),
                ("equip_name", models.CharField(max_length=100)),
                (
                    "status",
                    models.IntegerField(choices=[(0, "空闲"), (1, "忙碌")], default=0),
                ),
                ("processing_goodId", models.IntegerField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name="GoodList",
            fields=[
                ("goods_id", models.AutoField(primary_key=True, serialize=False)),
                ("goods_name", models.CharField(max_length=500)),
                ("goods_number", models.IntegerField(default=3)),
                ("goods_price", models.IntegerField(default=100)),
                ("goods_introduce", models.CharField(default="商品介绍", max_length=500)),
                ("goods_pic", models.CharField(default="1.png", max_length=500)),
                ("goods_stockNum", models.IntegerField(default=50)),
            ],
        ),
        migrations.CreateModel(
            name="UserList",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=500)),
                ("addr", models.CharField(max_length=500, null=True)),
                ("age", models.IntegerField(null=True)),
                (
                    "gender",
                    models.IntegerField(choices=[(1, "男"), (0, "女")], default=1),
                ),
                ("email", models.CharField(max_length=500, null=True)),
                ("phone", models.CharField(max_length=500, null=True)),
                ("pwd", models.CharField(max_length=500)),
                ("head_img", models.CharField(max_length=500, null=True)),
                (
                    "role",
                    models.IntegerField(
                        choices=[(1, "admin"), (0, "client")], default=0
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderList",
            fields=[
                ("order_id", models.AutoField(primary_key=True, serialize=False)),
                ("order_name", models.CharField(max_length=20, null=True)),
                (
                    "create_time",
                    models.DateTimeField(default=django.utils.timezone.localtime),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "待处理"), (1, "处理中"), (2, "已完成"), (3, "退回")]
                    ),
                ),
                (
                    "order_good",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="good_order",
                        to="UserApp.goodlist",
                        verbose_name="订购商品",
                    ),
                ),
                (
                    "buyer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_order",
                        to="UserApp.userlist",
                        verbose_name="买家",
                    ),
                ),
            ],
        ),
    ]
