# Generated by Django 5.1.7 on 2025-05-09 10:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("UserApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderlist",
            name="number",
            field=models.IntegerField(default=1),
        ),
    ]
