# Generated by Django 5.1.7 on 2025-05-28 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UserApp", "0002_orderlist_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="goodlist",
            name="goods_category",
            field=models.IntegerField(
                choices=[
                    (1, "智能小车"),
                    (2, "摄像头"),
                    (3, "传感器"),
                    (4, "标准件"),
                    (5, "定制件"),
                    (0, "其他"),
                ],
                default=0,
            ),
        ),
    ]
